# Generated by Django 5.0.1 on 2024-01-24 07:56

import martor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_comment_updated_alter_like_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=martor.models.MartorField(),
        ),
    ]
